resources:
  operator:
    limits:
      cpu: null
      memory: 1000Mi
    requests:
      cpu: 10m
      memory: 100Mi
  metricServer:
    limits:
      cpu: null
      memory: 1000Mi
    requests:
      cpu: 10m
      memory: 100Mi
  webhooks:
    limits:
      cpu: null
      memory: 1000Mi
    requests:
      cpu: 10m
      memory: 100Mi
